### ISSUE TITLE
Trim dependencies

### ISSUE THREAD

**Issue by joeroe** [joeroe/stratigraphr#16]
Do we really need?

Imports: 

- [x] rdpack, yes
- [ ] checkmate?
- [ ] cli, no, remove with #14 
- [ ] dplyr, maybe? https://www.tidyverse.org/blog/2023/04/performant-packages/
- [ ] glue, no, remove with #14
- [x] igraph, yes
- [ ] magrittr, no, replace with native pipe
- [ ] purrr, yes
- [ ] rcarbon, no, remove with #14
- [ ] readr, maybe? https://www.tidyverse.org/blog/2023/04/performant-packages/
- [x] relations, yes
- [x] rlang, yes
- [x] sets, yes
- [ ] stringr?
- [ ] tibble?
- [x] tidygraph, yes
- [ ] tidyr, surely not?
- [x] utils, yes

Suggests: 

- [ ] bchron, no, remove with #14
- [x] covr, yes
- [ ] fs?
- [ ] ggplot2, maybe not after #14
- [x] ggraph, yes
- [x] knitr, yes
- [x] oxcaar, yes
- [ ] readxl, surely not?
- [x] rmarkdown, yes
- [x] testthat, yes
